# Generated by Django 6.0.5 on 2026-05-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('sports', 'Sports'), ('luxury', 'Luxury')], max_length=50)),
                ('image', models.ImageField(upload_to='cars/')),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_week', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage_limit', models.IntegerField()),
                ('additional_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_rental', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('body_type', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('doors', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('toll_charges', models.CharField(max_length=50)),
                ('gearbox', models.CharField(max_length=50)),
                ('bags_capacity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=20)),
                ('dropoff_time', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('baby_seat', models.BooleanField(default=False)),
                ('payment_option', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_later', 'Pay Later')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.car')),
            ],
        ),
    ]
