# Generated by Django 6.0.5 on 2026-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('sports', 'Sports'), ('luxury', 'Luxury'), ('convertible', 'Convertible'), ('van', 'Van'), ('coupe', 'Coupe'), ('supercar', 'Supercar')], max_length=50),
        ),
    ]
