# Generated by Django 6.0.5 on 2026-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_car_features_alter_car_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='car',
            name='bags_capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='car',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='car',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='toll_charges',
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='overview',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='car',
            name='specs',
            field=models.JSONField(default=dict),
        ),
    ]
